# Site settings
title: "Patrick Haney, not a sausage"
email: patrick@hanerino.com
description: "Head of Innovation & Technology at AGNT, investor at Adventure Fund, NFT aficionado."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://patrickhaney.com" # the base hostname & protocol for your site
permalink: "/thoughts/:title/"
twitter_username: notasausage
github_username:  notasausage

# Build settings
markdown: kramdown
